version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=1
    volumes:
      - .:/app
